# Generated by Django 5.0.2 on 2024-02-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='otp_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
