# Generated by Django 5.0.2 on 2024-02-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_app', '0002_member_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='vote_casted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
