# Generated by Django 5.0.2 on 2024-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_app', '0003_member_vote_casted'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics/'),
        ),
    ]
